// Plain definitions for hover tooltips. Any non-business word on screen looks itself up here.
// Source of truth mirrored in vault: whatsoRAG/Vocabulary.md. Pal may edit wording.

export const DEFINITIONS: Record<string, string> = {
  rag: "Letting an AI answer using your own documents, not just its training.",
  graphrag: "RAG where facts are stored as a network of linked things.",
  hypergraphrag: "RAG where one fact can link many things at once.",
  raganything: "An all-in-one RAG that handles text, images, tables and more.",
  parse: "Turning a file into clean text the computer can use.",
  liteparse: "A fast local tool that parses PDFs and keeps where the text sits.",
  "doc-vlm": "An AI that reads a whole page image: text, tables, charts, layout.",
  ocr: "Reading text out of a picture or scan.",
  vision: "Having an AI look at an image and read or describe it.",
  transcribe: "Turning speech audio into text.",
  "freeze frame": "A still picture grabbed from a video.",
  chunk: "A small passage a document is split into.",
  overlap: "Repeating a little text between passages so context is not cut.",
  embed: "Turning text into numbers that capture its meaning.",
  vectorize: "Turning text into numbers that capture its meaning.",
  fingerprint: "A signature that identifies something: a speaker's voice, a writer's style, or the meaning-numbers of a text.",
  index: "A structure that makes searching those fingerprints fast.",
  "vector database": "A store that finds things by meaning.",
  "relational database": "A store of rows and columns (postgres / sql).",
  hypergraph: "A network where one link can join many things at once.",
  entity: "A thing that matters: a person, ingredient, company, place.",
  relationship: "A link between two entities.",
  canonical: "The one official name for something.",
  aka: "Also known as: the other names for the same thing.",
  dedup: "Removing duplicate copies.",
  normalize: "Making values consistent (units, spelling, format).",
  semantic: "By meaning, not exact words.",
  fuzzy: "Approximate matching that tolerates typos and variants.",
  rerank: "Reordering search results so the best ones come first.",
  multimodal: "Handling text, images, audio and video together.",
  "order aware": "Keeping track of time order and what is latest.",
  embeddings2: "A newer generation of embedding models (leaderboards shift fast, so 'best' is a moving target).",
  "episodic memory": "A memory of events over time: what happened and when, kept alongside meaning search.",
  "semantic memory": "A memory of what things mean, not tied to time.",
  raptor: "A method that summarizes long documents into layers so you can ask for the big picture or the fine detail.",
  hipporag: "A brain-inspired method that links facts into a memory and answers multi-part questions in one hop.",
  hybrid: "Searching by meaning and by exact keywords at the same time, then combining the results.",
  bm25: "A classic keyword search that ranks results by how well the words match.",
  colpali: "An AI that searches document pages as images, so tables and charts are not lost.",
  lazygraphrag: "A cheaper GraphRAG that waits to do the expensive AI work until you actually ask.",
  hypertsrag: "An early-stage method that adds 'when' and 'where' scoring on top of a hypergraph.",
  "summary tree": "Passages grouped and summarized into layers, from detail at the bottom to overview at the top.",
  "personalized pagerank": "A way to score which linked facts matter most for your specific question.",
  provenance: "A record of where each fact came from, so you can cite the source.",
  naive: "Naive chunking: split text into fixed pieces with no extra context. Simplest, but can cut an idea in half.",
  contextual: "Contextual chunking: add a little of the document's context to each piece before embedding, so it is not read in isolation.",
  late: "Late chunking: embed the whole document first, then split, so each piece carries the full-document context.",
  "bounding box": "The exact spot on a page (a box) where a fact was found, used to highlight the source.",
  enrich: "Adding extra detail from other sources to fill gaps.",
  "graph database": "A store of things (nodes) and the two-way links between them.",
  node: "One thing in a graph (an entity), connected to others by links.",
  route: "Deciding which store(s) and which path to search for a given question.",
  "path expansion": "Following the links out from your first hits to pull in related facts.",
  fusion: "Combining results that came back from several paths or stores into one set.",
  "hyperedge filtration": "Keeping only the many-at-once (n-ary) facts that are relevant to the question.",
  hops: "How many link-steps you travel out from the starting facts.",
  "priority queue": "A to-do list that always handles the most promising branch next.",
  "score and prune": "Scoring branches and dropping the weak ones early to stay fast.",
  "temporal coherence": "How well a fact fits the time and order the question is asking about.",
  "spatial overlap": "How much a fact's place on a page or image lines up with what is asked.",
  "structural importance": "How central a fact is in the network of links (well-connected facts count more).",
  "weighted simulation": "Combining several scoring factors, each with its own weight, into one final ranking.",
  "context segment extraction": "Pulling out the exact passages or segments to send as evidence.",
  "cross-encoder": "A slower, more accurate model that reads the question and a result together to judge the match.",
  "cross reference": "Checking a fact against other sources to confirm, compare, or link them.",
  "look up": "Fetching a specific record or fact directly by its key, not a fuzzy search.",
};

export function defineTerm(word: string): string | undefined {
  return DEFINITIONS[word.trim().toLowerCase()];
}
